#!/usr/bin/env python3
"""Tkinter scoreboard for MVP tournament result workbooks.

This app loads the Excel file generated by run_mvp_tournament.py, then displays:
- Top-line metrics (agents, matches, and average rates)
- A searchable, sortable summary table

Supported input: .xlsx files containing a sheet named "Summary".
"""

from __future__ import annotations

import argparse
import re
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk
from typing import Dict, List, Optional, Sequence
from xml.etree import ElementTree as ET
from zipfile import ZipFile


NS_MAIN = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
NS_REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
NS_PKG_REL = "http://schemas.openxmlformats.org/package/2006/relationships"


def _cell_ref_to_col_index(cell_ref: str) -> int:
    letters = "".join(ch for ch in cell_ref if ch.isalpha())
    value = 0
    for char in letters:
        value = value * 26 + (ord(char.upper()) - ord("A") + 1)
    return max(0, value - 1)


def _extract_cell_text(cell: ET.Element, shared_strings: Sequence[str]) -> str:
    cell_type = cell.get("t")
    if cell_type == "inlineStr":
        text_nodes = cell.findall(f"{{{NS_MAIN}}}is/{{{NS_MAIN}}}t")
        return "".join(node.text or "" for node in text_nodes)

    if cell_type == "s":
        value_node = cell.find(f"{{{NS_MAIN}}}v")
        if value_node is None or value_node.text is None:
            return ""
        try:
            index = int(value_node.text)
            return shared_strings[index] if 0 <= index < len(shared_strings) else ""
        except ValueError:
            return ""

    if cell_type == "b":
        value_node = cell.find(f"{{{NS_MAIN}}}v")
        return "TRUE" if value_node is not None and (value_node.text or "") == "1" else "FALSE"

    value_node = cell.find(f"{{{NS_MAIN}}}v")
    if value_node is not None and value_node.text is not None:
        return value_node.text

    # Fallback for string-rich cells without <v>
    text_nodes = cell.findall(f".//{{{NS_MAIN}}}t")
    return "".join(node.text or "" for node in text_nodes)


def _read_shared_strings(zip_file: ZipFile) -> List[str]:
    if "xl/sharedStrings.xml" not in zip_file.namelist():
        return []

    root = ET.fromstring(zip_file.read("xl/sharedStrings.xml"))
    strings: List[str] = []
    for si in root.findall(f"{{{NS_MAIN}}}si"):
        text_nodes = si.findall(f".//{{{NS_MAIN}}}t")
        strings.append("".join(node.text or "" for node in text_nodes))
    return strings


def _sheet_path_for_name(zip_file: ZipFile, sheet_name: str) -> Optional[str]:
    workbook = ET.fromstring(zip_file.read("xl/workbook.xml"))
    rels = ET.fromstring(zip_file.read("xl/_rels/workbook.xml.rels"))

    rel_map: Dict[str, str] = {}
    for rel in rels.findall(f"{{{NS_PKG_REL}}}Relationship"):
        rel_id = rel.get("Id")
        rel_target = rel.get("Target")
        if rel_id and rel_target:
            rel_map[rel_id] = rel_target

    for sheet in workbook.findall(f"{{{NS_MAIN}}}sheets/{{{NS_MAIN}}}sheet"):
        name = sheet.get("name")
        rel_id = sheet.get(f"{{{NS_REL}}}id")
        if name == sheet_name and rel_id and rel_id in rel_map:
            target = rel_map[rel_id]
            target = target.lstrip("/")
            if not target.startswith("xl/"):
                target = f"xl/{target}"
            return target

    return None


def read_xlsx_sheet_rows(file_path: Path, sheet_name: str) -> List[List[str]]:
    with ZipFile(file_path, "r") as zip_file:
        sheet_path = _sheet_path_for_name(zip_file, sheet_name)
        if sheet_path is None or sheet_path not in zip_file.namelist():
            raise ValueError(f"Sheet '{sheet_name}' not found in {file_path}")

        shared_strings = _read_shared_strings(zip_file)
        root = ET.fromstring(zip_file.read(sheet_path))
        rows: List[List[str]] = []

        for row in root.findall(f"{{{NS_MAIN}}}sheetData/{{{NS_MAIN}}}row"):
            values: Dict[int, str] = {}
            max_index = -1
            for cell in row.findall(f"{{{NS_MAIN}}}c"):
                ref = cell.get("r", "")
                col_index = _cell_ref_to_col_index(ref)
                max_index = max(max_index, col_index)
                values[col_index] = _extract_cell_text(cell, shared_strings)

            if max_index < 0:
                rows.append([])
                continue

            row_values = [""] * (max_index + 1)
            for idx, text in values.items():
                row_values[idx] = text
            rows.append(row_values)

    return rows


def parse_percent(value: str) -> float:
    match = re.search(r"([0-9]+(?:\.[0-9]+)?)", value or "")
    return float(match.group(1)) if match else 0.0


def to_int(value: str) -> int:
    try:
        return int(float(value))
    except (ValueError, TypeError):
        return 0


class TournamentScoreboardApp:
    def __init__(self, root: tk.Tk, initial_path: Optional[Path] = None):
        self.root = root
        self.root.title("MVP Tournament Scoreboard")
        self.root.geometry("1320x780")
        self.root.minsize(1120, 700)
        self.root.configure(bg="#f3f6fb")

        self.file_var = tk.StringVar(
            value=str(initial_path) if initial_path else "")
        self.status_var = tk.StringVar(
            value="Choose a result workbook and click Load.")
        self.current_file_path: Optional[Path] = None

        self.summary_rows: List[Dict[str, str]] = []
        self.filtered_rows: List[Dict[str, str]] = []
        self.columns: List[str] = []
        self.sort_column: Optional[str] = None
        self.sort_desc: bool = True

        self.metric_vars = {
            "agents": tk.StringVar(value="0"),
            "matches": tk.StringVar(value="0"),
            "overall_avg": tk.StringVar(value="0.00%"),
            "red_avg": tk.StringVar(value="0.00%"),
            "blue_avg": tk.StringVar(value="0.00%"),
        }

        self._setup_styles()
        self._build_ui()

        if initial_path:
            self.load_file(initial_path)

    def _build_ui(self) -> None:
        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(2, weight=1)

        top = ttk.Frame(self.root, padding=(
            14, 14, 14, 10), style="App.TFrame")
        top.grid(row=0, column=0, sticky="ew")
        top.columnconfigure(1, weight=1)

        title = ttk.Label(top, text="Tournament Scoreboard",
                          style="Title.TLabel")
        title.grid(row=0, column=0, columnspan=4, sticky="w", pady=(0, 8))

        self.file_label = ttk.Label(
            top, text="Result File:", style="Muted.TLabel")
        self.file_label.grid(
            row=1, column=0, padx=(0, 8), sticky="w")
        self.file_entry = ttk.Entry(
            top, textvariable=self.file_var, style="App.TEntry")
        self.file_entry.grid(row=1, column=1, sticky="ew")

        self.browse_button = ttk.Button(
            top, text="Browse", command=self.browse_file, style="App.TButton")
        self.browse_button.grid(
            row=1, column=2, padx=(8, 6))
        self.load_button = ttk.Button(
            top, text="Load", command=self.load_from_entry, style="Accent.TButton")
        self.load_button.grid(
            row=1, column=3)

        self.actions_frame = ttk.Frame(top, style="App.TFrame")
        self.actions_frame.grid(row=1, column=0, columnspan=4, sticky="e")

        self.change_button = ttk.Button(
            self.actions_frame,
            text="Change Result File",
            command=self.change_file,
            style="App.TButton",
        )
        self.change_button.grid(row=0, column=0, padx=(0, 8))

        self.reload_button = ttk.Button(
            self.actions_frame,
            text="Reload Current",
            command=self.reload_current,
            style="Accent.TButton",
            state="disabled",
        )
        self.reload_button.grid(row=0, column=1)

        self.actions_frame.grid_remove()

        cards = ttk.Frame(self.root, padding=(
            14, 0, 14, 10), style="App.TFrame")
        cards.grid(row=1, column=0, sticky="ew")
        for col in range(5):
            cards.columnconfigure(col, weight=1)

        self._metric_card(cards, 0, "Agents", self.metric_vars["agents"])
        self._metric_card(cards, 1, "Matches", self.metric_vars["matches"])
        self._metric_card(cards, 2, "Overall Avg",
                          self.metric_vars["overall_avg"])
        self._metric_card(cards, 3, "Red Avg", self.metric_vars["red_avg"])
        self._metric_card(cards, 4, "Blue Avg", self.metric_vars["blue_avg"])

        center = ttk.Frame(self.root, padding=(
            14, 0, 14, 10), style="App.TFrame")
        center.grid(row=2, column=0, sticky="nsew")
        center.columnconfigure(0, weight=1)
        center.rowconfigure(1, weight=1)

        toolbar = ttk.Frame(center, style="App.TFrame")
        toolbar.grid(row=0, column=0, sticky="ew", pady=(0, 8))
        ttk.Label(
            toolbar,
            text="Tip: Click a column header to sort.",
            style="Muted.TLabel",
        ).grid(row=0, column=0, sticky="w")

        table_frame = ttk.Frame(center, style="App.TFrame")
        table_frame.grid(row=1, column=0, sticky="nsew")
        table_frame.columnconfigure(0, weight=1)
        table_frame.rowconfigure(0, weight=1)

        self.tree = ttk.Treeview(
            table_frame, show="headings", style="Score.Treeview")
        self.tree.grid(row=0, column=0, sticky="nsew")

        yscroll = ttk.Scrollbar(
            table_frame, orient="vertical", command=self.tree.yview)
        xscroll = ttk.Scrollbar(
            table_frame, orient="horizontal", command=self.tree.xview)
        self.tree.configure(yscrollcommand=yscroll.set,
                            xscrollcommand=xscroll.set)
        yscroll.grid(row=0, column=1, sticky="ns")
        xscroll.grid(row=1, column=0, sticky="ew")

        status = ttk.Label(
            self.root,
            textvariable=self.status_var,
            anchor="w",
            padding=(14, 4, 14, 10),
            style="Muted.TLabel",
        )
        status.grid(row=3, column=0, sticky="ew")

    def _setup_styles(self) -> None:
        style = ttk.Style(self.root)
        style.theme_use("clam")

        style.configure("App.TFrame", background="#f3f6fb")
        style.configure("Title.TLabel", background="#f3f6fb",
                        foreground="#1b2a4a", font=("Segoe UI", 17, "bold"))
        style.configure("Muted.TLabel", background="#f3f6fb",
                        foreground="#5a6785", font=("Segoe UI", 10))
        style.configure("App.TEntry", fieldbackground="#ffffff",
                        bordercolor="#d8e1f0", insertcolor="#1b2a4a")

        style.configure("App.TButton", padding=(10, 6),
                        font=("Segoe UI", 10, "bold"))
        style.configure("Accent.TButton", padding=(12, 6), font=(
            "Segoe UI", 10, "bold"), foreground="#ffffff", background="#2f6fed")
        style.map(
            "Accent.TButton",
            background=[("active", "#255bd0"), ("pressed", "#224db6")],
            foreground=[("disabled", "#ffffff")],
        )

        style.configure(
            "Score.Treeview",
            background="#ffffff",
            fieldbackground="#ffffff",
            foreground="#1e2a44",
            bordercolor="#d8e1f0",
            rowheight=30,
            font=("Segoe UI", 10),
        )
        style.configure(
            "Score.Treeview.Heading",
            background="#eaf0fb",
            foreground="#1b2a4a",
            relief="flat",
            font=("Segoe UI", 10, "bold"),
        )
        style.map("Score.Treeview.Heading", background=[("active", "#dde7fb")])

    def _metric_card(self, parent: ttk.Frame, column: int, label: str, value_var: tk.StringVar) -> None:
        card_colors = [
            ("#1f3c88", "#ffffff"),
            ("#165d6d", "#ffffff"),
            ("#2f6fed", "#ffffff"),
            ("#c43e3e", "#ffffff"),
            ("#2a8b77", "#ffffff"),
        ]
        bg, fg = card_colors[column % len(card_colors)]

        frame = tk.Frame(parent, bg=bg, bd=0, highlightthickness=0)
        frame.grid(row=0, column=column, padx=(
            0 if column == 0 else 10, 0), sticky="nsew")
        frame.grid_propagate(False)
        frame.configure(height=84)

        title = tk.Label(frame, text=label, bg=bg, fg="#dce7ff",
                         font=("Segoe UI", 10, "bold"))
        title.pack(anchor="w", padx=12, pady=(10, 2))
        value = tk.Label(frame, textvariable=value_var, bg=bg,
                         fg=fg, font=("Segoe UI", 18, "bold"))
        value.pack(anchor="w", padx=12)

    def browse_file(self) -> None:
        selected = filedialog.askopenfilename(
            title="Select Tournament Result Workbook",
            filetypes=[("Excel files", "*.xlsx"), ("All files", "*.*")],
        )
        if selected:
            self.file_var.set(selected)

    def change_file(self) -> None:
        selected = filedialog.askopenfilename(
            title="Select Tournament Result Workbook",
            filetypes=[("Excel files", "*.xlsx"), ("All files", "*.*")],
        )
        if not selected:
            return

        selected_path = Path(selected).expanduser()
        self.file_var.set(str(selected_path))
        self.load_file(selected_path)

    def reload_current(self) -> None:
        if self.current_file_path is None:
            messagebox.showinfo(
                "No file", "No result file is currently loaded.")
            return
        self.load_file(self.current_file_path)

    def _set_file_controls_loaded_mode(self, loaded: bool) -> None:
        if loaded:
            self.file_label.grid_remove()
            self.file_entry.grid_remove()
            self.browse_button.grid_remove()
            self.load_button.grid_remove()
            self.actions_frame.grid()
            self.reload_button.configure(state="normal")
        else:
            self.actions_frame.grid_remove()
            self.file_label.grid()
            self.file_entry.grid()
            self.browse_button.grid()
            self.load_button.grid()

    def load_from_entry(self) -> None:
        raw = self.file_var.get().strip()
        if not raw:
            messagebox.showwarning(
                "Missing path", "Please provide a result file path.")
            return
        self.load_file(Path(raw).expanduser())

    def load_file(self, file_path: Path) -> None:
        if not file_path.exists():
            messagebox.showerror(
                "File not found", f"Cannot find file:\n{file_path}")
            return

        try:
            rows = read_xlsx_sheet_rows(file_path, "Summary")
        except Exception as exc:
            messagebox.showerror(
                "Load failed", f"Failed to read workbook:\n{exc}")
            return

        if not rows:
            messagebox.showerror("Invalid workbook", "Summary sheet is empty.")
            return

        header = [value.strip() for value in rows[0]]
        data_rows = [row for row in rows[1:]
                     if any(cell.strip() for cell in row)]

        records: List[Dict[str, str]] = []
        for row in data_rows:
            row_extended = list(row) + [""] * max(0, len(header) - len(row))
            records.append({header[idx]: row_extended[idx]
                           for idx in range(len(header))})

        required = {"overall_success_rate",
                    "red_success_rate", "blue_success_rate"}
        if not required.issubset(set(header)):
            messagebox.showerror(
                "Invalid Summary Sheet",
                "Summary sheet is missing required columns.\nExpected at least: overall_success_rate, red_success_rate, blue_success_rate",
            )
            return

        for row in records:
            group_name = (row.get("group_name", "") or "").strip()
            fallback_agent = (row.get("agent", "") or "").strip()
            row["display_group_name"] = group_name if group_name else (
                fallback_agent or "(Unnamed Team)")
            row["team_members"] = (row.get("student_name", "") or "").strip()

        self.summary_rows = records
        self.columns = [
            "display_group_name",
            "team_members",
            "overall_success_rate",
            "red_success_rate",
            "blue_success_rate",
        ]
        self.columns = [col for col in self.columns if col in header]
        # display_group_name and team_members are derived fields, always include.
        if "display_group_name" not in self.columns:
            self.columns.insert(0, "display_group_name")
        if "team_members" not in self.columns:
            self.columns.insert(1, "team_members")

        self._update_metrics()
        self._configure_table_columns()
        self.sort_column = "overall_success_rate"
        self.sort_desc = True
        self.refresh_table()

        self.current_file_path = file_path
        self.file_var.set(str(file_path))
        self._set_file_controls_loaded_mode(True)

        self.status_var.set(
            f"Loaded {len(self.summary_rows)} teams. Use 'Change Result File' or 'Reload Current' anytime.")

    def _update_metrics(self) -> None:
        count = len(self.summary_rows)
        total_matches = sum(to_int(row.get("total_games", "0"))
                            for row in self.summary_rows) // 2

        overall_avg = sum(parse_percent(row.get("overall_success_rate", "0"))
                          for row in self.summary_rows) / count if count else 0.0
        red_avg = sum(parse_percent(row.get("red_success_rate", "0"))
                      for row in self.summary_rows) / count if count else 0.0
        blue_avg = sum(parse_percent(row.get("blue_success_rate", "0"))
                       for row in self.summary_rows) / count if count else 0.0

        self.metric_vars["agents"].set(str(count))
        self.metric_vars["matches"].set(str(total_matches))
        self.metric_vars["overall_avg"].set(f"{overall_avg:.2f}%")
        self.metric_vars["red_avg"].set(f"{red_avg:.2f}%")
        self.metric_vars["blue_avg"].set(f"{blue_avg:.2f}%")

    def _configure_table_columns(self) -> None:
        self.tree.delete(*self.tree.get_children())
        self.tree["columns"] = self.columns

        header_map = {
            "display_group_name": "Group Name",
            "team_members": "Team Members",
            "overall_success_rate": "Overall Rate",
            "red_success_rate": "Red Rate",
            "blue_success_rate": "Blue Rate",
        }

        for col in self.columns:
            title = header_map.get(col, col.replace("_", " ").title())
            self.tree.heading(
                col, text=title, command=lambda c=col: self.sort_by(c))
            width = 130
            anchor = "center"
            if col in {"display_group_name", "team_members"}:
                width = 270 if col == "display_group_name" else 360
                anchor = "w"
            self.tree.column(col, width=width, minwidth=90, anchor=anchor)

        self.tree.tag_configure("odd", background="#ffffff")
        self.tree.tag_configure("even", background="#f8fbff")

    def sort_by(self, column: str) -> None:
        if self.sort_column == column:
            self.sort_desc = not self.sort_desc
        else:
            self.sort_column = column
            self.sort_desc = True
        self.refresh_table()

    def refresh_table(self) -> None:
        rows = self.summary_rows

        if self.sort_column:
            if self.sort_column.endswith("_success_rate"):
                rows = sorted(
                    rows,
                    key=lambda item: parse_percent(
                        item.get(self.sort_column or "", "0")),
                    reverse=self.sort_desc,
                )
            else:
                rows = sorted(
                    rows,
                    key=lambda item: item.get(
                        self.sort_column or "", "").lower(),
                    reverse=self.sort_desc,
                )

        self.filtered_rows = rows
        self.tree.delete(*self.tree.get_children())
        for index, row in enumerate(self.filtered_rows):
            values = [row.get(col, "") for col in self.columns]
            tag = "even" if index % 2 == 0 else "odd"
            self.tree.insert("", "end", values=values, tags=(tag,))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Launch tkinter scoreboard for tournament result workbook.")
    parser.add_argument(
        "--file",
        type=str,
        default=None,
        help="Path to result workbook (.xlsx).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    initial = Path(args.file).expanduser() if args.file else None

    root = tk.Tk()
    app = TournamentScoreboardApp(root, initial_path=initial)
    root.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
